Repository akvo/akvo-lumen, pull requests merged in 2018-11, with the labels that each got.

#1746 [#1745] Handle middleware args as vectors
  backend/src/akvo/lumen/component/handler.clj
Labels: in progress

#1750 [#1742] Mailjet v3 emailer
  backend/dev/resources/dev.edn
  backend/dev/src/dev.clj
  backend/resources/akvo/lumen/config.edn
  backend/src/akvo/lumen/component/emailer.clj
  backend/src/akvo/lumen/config.clj
  backend/src/akvo/lumen/main.clj
  ci/k8s/deployment.yaml.template
Labels: in progress

#1752 Clean up blue-green-gateway
  ci/k8s/blue-green-gateway.yaml
Labels: in progress

#1741 Issue/1710 speed up builds
  .travis.yml
  README.dev.md
  backend/Dockerfile
  backend/Dockerfile-dev
  backend/dev_helpers/bash/headers.sh
  backend/import-and-run.sh
  backend/maybe-import-and-java-jar.sh
  backend/run-as-user.sh
  backend/wait-for-dependencies.sh
  ci/build.sh
  ci/e2e-test.sh
  ci/helpers/wait-for-docker-compose-to-start.sh
  client/Dockerfile-dev
  client/e2e-test/Dockerfile
  client/e2e-test/package-lock.json
  client/e2e-test/package.json
  client/e2e-test/run-as-user.sh
  client/e2e-test/run.sh
  client/e2e-test/sample-data-1.csv
  client/install-and-start.sh
  client/package-lock.json
  client/run-as-user.sh
  docker-compose.ci.yml
  docker-compose.override.yml
  docker-compose.yml
  keycloak/Dockerfile
  keycloak/akvo.json
  postgres/Dockerfile
  postgres/provision/helpers/create-extensions.sql
  postgres/provision/helpers/create-lumen.sql
  postgres/provision/helpers/create-tenants.sql
  postgres/provision/pg.conf
  postgres/provision/pg_hba.conf
  postgres/provision/server.crt
  postgres/provision/server.key
  postgres/provision/setup.sh
  setup-env.sh
Labels: in progress

#1758 [#1710] Fix ubound variable
  backend/maybe-import-and-java-jar.sh
Labels: in progress

#1755 New visualization types #1734 scatter
  backend/src/akvo/lumen/lib/aggregation/scatter.clj
  backend/test/resources/scatter.csv
  client/src/components/charts/Chart.jsx
  client/src/components/charts/ScatterChart.jsx
  client/src/components/charts/Tooltip.jsx
  client/src/components/visualisation/VisualisationEditor.jsx
  client/src/components/visualisation/VisualisationEditor.scss
  client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
  client/src/constants/Visualisation/scatterSpecTemplate.js
  client/src/constants/Visualisation/visualisationColumnMappings.js
  client/src/translations/en.json
  client/src/translations/es.json
  client/src/translations/fr.json
Labels: in progress

#1760 Issue/1710 wait for deps
  backend/Dockerfile
  backend/run-server.sh
  docker-compose.ci.yml
Labels: in progress

#1759 Discard failing transformations in history transformation log [client]
  client/src/containers/Dataset.jsx
Labels: client, in progress

#1761 [#1276] Update eastwood and fix warnings
  backend/project.clj
  backend/src/akvo/lumen/component/hikaricp.clj
Labels: in progress

#1763 issue/1408 Refactor and Add support for deleting failed datasets
  backend/resources/akvo/lumen/config.edn
  backend/src/akvo/lumen/data-source.sql
  backend/src/akvo/lumen/endpoint/data_source.clj
  backend/src/akvo/lumen/endpoint/job_execution.clj
  backend/src/akvo/lumen/job-execution.sql
  backend/src/akvo/lumen/lib/data_source.clj
  backend/src/akvo/lumen/lib/job_execution.clj
  backend/src/akvo/lumen/lib/job_execution_impl.clj
  client/src/actions/dataset.js
  client/src/components/Library.jsx
Labels: in progress

#1765 Adapt nil values [#797]
  backend/src/akvo/lumen/transformation/split_column.clj
  backend/test/akvo/lumen/transformation_test.clj
  backend/test/resources/split_column.csv
Labels: in progress

#1768 [#1762] Handle update errors properly
  backend/src/akvo/lumen/dataset.clj
  backend/src/akvo/lumen/endpoint/dataset.clj
  backend/src/akvo/lumen/import.clj
  backend/src/akvo/lumen/update.clj
Labels: in progress

#1766 #1734 scatter improvements fixes
  client/src/components/charts/ScatterChart.jsx
  client/src/containers/Main.scss
  client/src/styles/style.global.scss
Labels: in progress

#1769 #1734 scatter colorpicker improvements
  client/src/components/charts/Chart.jsx
  client/src/components/charts/Legend.jsx
  client/src/components/charts/ScatterChart.jsx
Labels: in progress

#1771 Improve error messages on undoing transformations
  backend/src/akvo/lumen/transformation/engine.clj
Labels: in progress

#1773 Adapt engine/next-column-index to keywordized column
  backend/src/akvo/lumen/transformation/engine.clj
Labels: in progress

#1775 Stringify columns keys [#797]
  backend/src/akvo/lumen/transformation/engine.clj
  backend/src/akvo/lumen/transformation/split_column.clj
Labels: in progress

#1780 Add support for "SCAN" flow type values [#1778]
  backend/src/akvo/lumen/import/flow_v2.clj
Labels: in progress

#1783 React is running in production mode, but dead code elimination has no…
  client/webpack.config.prod.js
Labels: in progress

#1782 Make dev work on OS X (Connect #1781)
  backend/.dir-locals.el
  docker-compose.override.yml
Labels: in progress

#1788 Fix failing SQL update with single quote or dollar sign values (Connect #1785)
  backend/src/akvo/lumen/postgres.clj
  backend/src/akvo/lumen/transformation/multiple_column/caddisfly.clj
  backend/src/akvo/lumen/transformation/split_column.clj
  backend/test/akvo/lumen/transformation_test.clj
  backend/test/resources/split_column_1785.csv
Labels: in progress

#1777 Filter library and dataset responses (Connect #1776)
  backend/src/akvo/lumen/dataset.sql
Labels: in progress, ready for testing

#1795 Debugging exporter-service http call
  backend/src/akvo/lumen/lib/export.clj
  exporter/index.js
Labels: in progress

#1792 Add clojure spec gradually (Connect #1441)
  backend/dev/src/dev.clj
  backend/project.clj
  backend/src/akvo/lumen/component/caddisfly.clj
  backend/src/akvo/lumen/import.clj
  backend/src/akvo/lumen/import/common.clj
  backend/src/akvo/lumen/lib/multiple_column.clj
  backend/src/akvo/lumen/specs/components.clj
  backend/src/akvo/lumen/specs/components/caddisfly.clj
  backend/src/akvo/lumen/transformation/merge_datasets.clj
  backend/src/akvo/lumen/transformation/multiple_column.clj
  backend/src/akvo/lumen/transformation/multiple_column/caddisfly.clj
  backend/src/akvo/lumen/update.clj
  backend/test/akvo/lumen/component/caddisfly_test.clj
  backend/test/akvo/lumen/test_utils.clj
  backend/test/akvo/lumen/transformation_test.clj
Labels: backend, in progress, specs

#1797 Tidy up namespaces related to a.l.endpoint ns (Connect #1796)
  backend/dev/src/dev.clj
  backend/src/akvo/lumen/endpoint/aggregation.clj
  backend/src/akvo/lumen/endpoint/commons.clj
  backend/src/akvo/lumen/endpoint/commons/http.clj
  backend/src/akvo/lumen/endpoint/commons/variant.clj
  backend/src/akvo/lumen/endpoint/healthz.clj
  backend/src/akvo/lumen/endpoint/invite.clj
  backend/src/akvo/lumen/endpoint/library.clj
  backend/src/akvo/lumen/endpoint/user.clj
  backend/src/akvo/lumen/main.clj
  backend/test/akvo/lumen/endpoint/collection_test.clj
  backend/test/akvo/lumen/endpoint/dashboard_test.clj
  backend/test/akvo/lumen/endpoint/public_test.clj
  backend/test/akvo/lumen/endpoint/share_test.clj
  backend/test/akvo/lumen/lib/user_test.clj
Labels: in progress

#1799 Tidy up namespaces related to a.l.dataset ns (Connect #1796)
  backend/src/akvo/lumen/endpoint/dataset.clj
  backend/src/akvo/lumen/endpoint/library.clj
  backend/src/akvo/lumen/import.clj
  backend/src/akvo/lumen/lib/aggregation.clj
  backend/src/akvo/lumen/lib/aggregation/bar.clj
  backend/src/akvo/lumen/lib/aggregation/line.clj
  backend/src/akvo/lumen/lib/aggregation/pie.clj
  backend/src/akvo/lumen/lib/aggregation/pivot.clj
  backend/src/akvo/lumen/lib/aggregation/scatter.clj
  backend/src/akvo/lumen/lib/dataset.clj
  backend/src/akvo/lumen/lib/dataset.sql
  backend/src/akvo/lumen/lib/dataset/utils.clj
  backend/src/akvo/lumen/lib/public_impl.clj
  backend/src/akvo/lumen/lib/visualisation/map_config.clj
  backend/src/akvo/lumen/lib/visualisation/maps.clj
  backend/src/akvo/lumen/transformation/derive.clj
  backend/src/akvo/lumen/transformation/merge_datasets.clj
  backend/src/akvo/lumen/transformation/multiple_column.clj
  backend/src/akvo/lumen/update.clj
  backend/test/akvo/lumen/endpoint/collection_test.clj
  backend/test/akvo/lumen/endpoint/share_test.clj
Labels: in progress

#1800 [#1796] Move akvo.lumen.import logic inside akvo.lumen.lib
  backend/src/akvo/lumen/lib/dataset.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/lib/import/common.clj
  backend/src/akvo/lumen/lib/import/csv.clj
  backend/src/akvo/lumen/lib/import/flow.clj
  backend/src/akvo/lumen/lib/import/flow_common.clj
  backend/src/akvo/lumen/lib/import/flow_v2.clj
  backend/src/akvo/lumen/lib/import/flow_v3.clj
  backend/src/akvo/lumen/lib/raster_impl.clj
  backend/src/akvo/lumen/transformation/geo.clj
  backend/src/akvo/lumen/update.clj
  backend/test/akvo/lumen/lib/import/csv_test.clj
  backend/test/akvo/lumen/lib/import/raster_test.clj
  backend/test/akvo/lumen/test_utils.clj
Labels: in progress

#1801 Refactor akvo.lumen.boundary.error-tracker (connect #1796)
  backend/src/akvo/lumen/boundary/error_tracker.clj
  backend/src/akvo/lumen/component/error_tracker.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/update.clj
Labels: in progress

#1802 Exporter retry functionality fixes #1717
  exporter/index.js
Labels: in progress

#1803 [#1796]Move akvo/lumen/*.sql files into akvo/lumen/lib
  backend/src/akvo/lumen/endpoint/split_column.clj
  backend/src/akvo/lumen/lib/data-source.sql
  backend/src/akvo/lumen/lib/data_source.clj
  backend/src/akvo/lumen/lib/dataset.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/lib/job-execution.sql
  backend/src/akvo/lumen/lib/job_execution.clj
  backend/src/akvo/lumen/lib/raster_impl.clj
  backend/src/akvo/lumen/lib/transformation.sql
  backend/src/akvo/lumen/transformation.clj
  backend/src/akvo/lumen/transformation/engine.clj
  backend/src/akvo/lumen/transformation/merge_datasets.clj
  backend/src/akvo/lumen/transformation/multiple_column/caddisfly.clj
  backend/src/akvo/lumen/transformation/reverse_geocode.clj
  backend/src/akvo/lumen/transformation/split_column.clj
  backend/src/akvo/lumen/update.clj
  backend/test/akvo/lumen/endpoint/share_test.clj
  backend/test/akvo/lumen/lib/import/csv_test.clj
  backend/test/akvo/lumen/test_utils.clj
  backend/test/akvo/lumen/transformation_test.clj
Labels: in progress

#1804 [#1796]Move akvo.lumen.update ns to akvo.lumen.lib.update
  backend/src/akvo/lumen/lib/dataset.clj
  backend/src/akvo/lumen/lib/raster_impl.clj
  backend/src/akvo/lumen/lib/update.clj
  backend/src/akvo/lumen/transformation/derive.clj
  backend/test/akvo/lumen/lib/update_test.clj
  backend/test/akvo/lumen/transformation/derive_test.clj
Labels: in progress

#1810 [#1808] Ensure multiple-type and multiple-id
  backend/src/akvo/lumen/lib/update.clj
Labels: backend, bug, in progress

#1805 Move akvo.lumen.transformation logic into akvo.lumen.lib
  backend/src/akvo/lumen/endpoint/split_column.clj
  backend/src/akvo/lumen/endpoint/transformation.clj
  backend/src/akvo/lumen/lib/dataset.clj
  backend/src/akvo/lumen/lib/transformation.clj
  backend/src/akvo/lumen/lib/transformation/change_datatype.clj
  backend/src/akvo/lumen/lib/transformation/change_datatype.sql
  backend/src/akvo/lumen/lib/transformation/combine.clj
  backend/src/akvo/lumen/lib/transformation/combine.sql
  backend/src/akvo/lumen/lib/transformation/delete_column.clj
  backend/src/akvo/lumen/lib/transformation/derive.clj
  backend/src/akvo/lumen/lib/transformation/derive.sql
  backend/src/akvo/lumen/lib/transformation/derive/js_engine.clj
  backend/src/akvo/lumen/lib/transformation/engine.clj
  backend/src/akvo/lumen/lib/transformation/engine.sql
  backend/src/akvo/lumen/lib/transformation/filter_column.clj
  backend/src/akvo/lumen/lib/transformation/filter_column.sql
  backend/src/akvo/lumen/lib/transformation/geo.clj
  backend/src/akvo/lumen/lib/transformation/geo.sql
  backend/src/akvo/lumen/lib/transformation/merge_datasets.clj
  backend/src/akvo/lumen/lib/transformation/multiple_column.clj
  backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj
  backend/src/akvo/lumen/lib/transformation/rename_column.clj
  backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj
  backend/src/akvo/lumen/lib/transformation/reverse_geocode.sql
  backend/src/akvo/lumen/lib/transformation/sort_column.clj
  backend/src/akvo/lumen/lib/transformation/sort_column.sql
  backend/src/akvo/lumen/lib/transformation/split_column.clj
  backend/src/akvo/lumen/lib/transformation/text.clj
  backend/src/akvo/lumen/lib/transformation/text.sql
  backend/src/akvo/lumen/lib/update.clj
  backend/src/akvo/lumen/lib/visualisation/maps.clj
  backend/test/akvo/lumen/lib/pivot_test.clj
  backend/test/akvo/lumen/lib/transformation/derive_test.clj
  backend/test/akvo/lumen/lib/transformation/engine_test.clj
  backend/test/akvo/lumen/lib/transformation/engine_test.sql
  backend/test/akvo/lumen/lib/transformation/split_column_test.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
  backend/test/akvo/lumen/lib/transformation_test.sql
  backend/test/akvo/lumen/lib/visualisation/maps_test.clj
Labels: in progress

#1807 [#1203] Fixes handling of Host, Origin http headers
  backend/project.clj
Labels: in progress

#1811 Remove indirection in akvo.lumen.lib/* namespaces (Connect #1796)
  backend/src/akvo/lumen/admin/add_tenant.clj
  backend/src/akvo/lumen/endpoint/invite.clj
  backend/src/akvo/lumen/lib/collection.clj
  backend/src/akvo/lumen/lib/collection_impl.clj
  backend/src/akvo/lumen/lib/dashboard.clj
  backend/src/akvo/lumen/lib/dashboard_impl.clj
  backend/src/akvo/lumen/lib/public.clj
  backend/src/akvo/lumen/lib/public_impl.clj
  backend/src/akvo/lumen/lib/raster.clj
  backend/src/akvo/lumen/lib/raster_impl.clj
  backend/src/akvo/lumen/lib/share.clj
  backend/src/akvo/lumen/lib/share_impl.clj
  backend/src/akvo/lumen/lib/tier.clj
  backend/src/akvo/lumen/lib/tier_impl.clj
  backend/src/akvo/lumen/lib/user.clj
  backend/src/akvo/lumen/lib/user_impl.clj
  backend/src/akvo/lumen/lib/visualisation.clj
  backend/src/akvo/lumen/lib/visualisation_impl.clj
  backend/test/akvo/lumen/endpoint/dashboard_test.clj
  backend/test/akvo/lumen/endpoint/public_test.clj
  backend/test/akvo/lumen/lib/user_test.clj
Labels: in progress

#1814 [#1796] Remove akvo.lumen.script.encrypt-db-uris
  backend/src/akvo/lumen/script/encrypt_db_uris.clj
Labels: in progress

#1815 [#1796] Move current protocols to akvo.lumen.protocols ns
  backend/src/akvo/lumen/component/emailer.clj
  backend/src/akvo/lumen/component/error_tracker.clj
  backend/src/akvo/lumen/component/keycloak.clj
  backend/src/akvo/lumen/component/tenant_manager.clj
  backend/src/akvo/lumen/endpoint/aggregation.clj
  backend/src/akvo/lumen/endpoint/collection.clj
  backend/src/akvo/lumen/endpoint/dashboard.clj
  backend/src/akvo/lumen/endpoint/data_source.clj
  backend/src/akvo/lumen/endpoint/dataset.clj
  backend/src/akvo/lumen/endpoint/invite.clj
  backend/src/akvo/lumen/endpoint/job_execution.clj
  backend/src/akvo/lumen/endpoint/library.clj
  backend/src/akvo/lumen/endpoint/public.clj
  backend/src/akvo/lumen/endpoint/raster.clj
  backend/src/akvo/lumen/endpoint/resource.clj
  backend/src/akvo/lumen/endpoint/share.clj
  backend/src/akvo/lumen/endpoint/split_column.clj
  backend/src/akvo/lumen/endpoint/tier.clj
  backend/src/akvo/lumen/endpoint/transformation.clj
  backend/src/akvo/lumen/endpoint/visualisation.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/lib/import/common.clj
  backend/src/akvo/lumen/lib/import/csv.clj
  backend/src/akvo/lumen/lib/import/flow.clj
  backend/src/akvo/lumen/lib/import/flow_common.clj
  backend/src/akvo/lumen/lib/import/flow_v2.clj
  backend/src/akvo/lumen/lib/update.clj
  backend/src/akvo/lumen/lib/user.clj
  backend/src/akvo/lumen/protocols.clj
Labels: in progress

#1806 Refactor construct config logic (Connect #1796)
  backend/dev/src/dev.clj
  backend/src/akvo/lumen/config.clj
  backend/src/akvo/lumen/migrate.clj
  backend/src/akvo/lumen/util/system.clj
Labels: in progress

#1816 Move middleware logic to its related namespaces (connect #1796)
  backend/dev/resources/dev.edn
  backend/dev/src/dev.clj
  backend/resources/akvo/lumen/config.edn
  backend/src/akvo/lumen/auth.clj
  backend/src/akvo/lumen/component/error_tracker.clj
  backend/src/akvo/lumen/component/handler.clj
  backend/src/akvo/lumen/component/tenant_manager.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/main.clj
  backend/src/akvo/lumen/middleware.clj
Labels: in progress

#1793 Bubble Chart (Connect #1787)
  backend/src/akvo/lumen/lib/aggregation.clj
  backend/src/akvo/lumen/lib/aggregation/bubble.clj
  client/src/components/charts/AsyncVisualisationViewer.jsx
  client/src/components/charts/BubbleChart.jsx
  client/src/components/charts/Chart.jsx
  client/src/components/charts/Chart.stories.jsx
  client/src/components/charts/Legend.jsx
  client/src/components/charts/LineChart.jsx
  client/src/components/charts/PieChart.jsx
  client/src/components/charts/ScatterChart.jsx
  client/src/components/charts/SimpleBarChart.jsx
  client/src/components/charts/StackedBarChart.jsx
  client/src/components/charts/VisualisationViewer.jsx
  client/src/components/common/ColorPicker.jsx
  client/src/components/common/Popover.jsx
  client/src/components/visualisation/VisualisationEditor.jsx
  client/src/components/visualisation/VisualisationPreview.jsx
  client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx
  client/src/components/visualisation/configMenu/ConfigMenu.jsx
  client/src/constants/Visualisation/bubbleSpecTemplate.js
  client/src/constants/Visualisation/visualisationColumnMappings.js
  client/src/constants/Visualisation/visualisationTypes.js
  client/src/containers/Visualisation.jsx
  client/src/styles/img/icon-128-visualisation-bubble.png
Labels: in progress

#1822 #1787 bubble vis fixes
  backend/src/akvo/lumen/lib/aggregation/bubble.clj
  backend/src/akvo/lumen/lib/public.clj
  client/src/components/visualisation/VisualisationEditor.jsx
  client/src/components/visualisation/VisualisationPreview.jsx
  client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx
Labels: in progress
