Repository akvo/akvo-lumen, pull requests merged in 2019-03, with the labels that each got.

#2017 [#2012] Horizontalbarcharts supports exporting
  client/package-lock.json
  client/src/components/charts/SimpleBarChartHorizontal.jsx
  client/src/utilities/visualisation.js
Labels: in progress

#2018 [#2012] Fixed stacked horizontal bars
  client/src/components/charts/StackedBarChartHorizontal.jsx
Labels: in progress

#2019 [#1694] Use default Sentry env vars
  ci/k8s/deployment.yaml.template
  client/src/containers/Dashboard.jsx
  exporter/index.js
Labels: in progress

#2020 [#1694] Refactor env vars in exporter
  ci/k8s/deployment.yaml.template
  exporter/index.js
Labels: in progress

#2021 [#1694] Remove debugg statements
  exporter/index.js
Labels: in progress

#2023 Issue/2022 exporter feature flag
  client/src/components/dashboard/DashboardHeader.jsx
  client/src/components/visualisation/VisualisationHeader.jsx
  client/src/containers/Dashboard.jsx
  client/src/containers/Dashboard.scss
  exporter/index.js
Labels: in progress

#2025 Add proper :path to monitoring
  backend/resources/akvo/lumen/config.edn
  backend/src/akvo/lumen/monitoring.clj
  backend/test/akvo/lumen/endpoints_test.clj
  backend/test/resources/endpoints-test.edn
Labels: in progress

#2030 Comments reviewed
  backend/dev/resources/dev.edn
  backend/resources/akvo/lumen/config.edn
  backend/src/akvo/lumen/component/handler.clj
  backend/test/resources/endpoints-test.edn
Labels: in progress

#1921 Use Reitit as declarative routing library
  backend/dev/resources/dev.edn
  backend/dev/src/dev.clj
  backend/dev/src/dev/commons.clj
  backend/project.clj
  backend/resources/akvo/lumen/config.edn
  backend/src/akvo/lumen/auth.clj
  backend/src/akvo/lumen/component/emailer.clj
  backend/src/akvo/lumen/component/handler.clj
  backend/src/akvo/lumen/endpoint/aggregation.clj
  backend/src/akvo/lumen/endpoint/collection.clj
  backend/src/akvo/lumen/endpoint/commons/http.clj
  backend/src/akvo/lumen/endpoint/dashboard.clj
  backend/src/akvo/lumen/endpoint/data_source.clj
  backend/src/akvo/lumen/endpoint/dataset.clj
  backend/src/akvo/lumen/endpoint/env.clj
  backend/src/akvo/lumen/endpoint/export.clj
  backend/src/akvo/lumen/endpoint/files.clj
  backend/src/akvo/lumen/endpoint/healthz.clj
  backend/src/akvo/lumen/endpoint/invite.clj
  backend/src/akvo/lumen/endpoint/job_execution.clj
  backend/src/akvo/lumen/endpoint/library.clj
  backend/src/akvo/lumen/endpoint/multiple_column.clj
  backend/src/akvo/lumen/endpoint/public.clj
  backend/src/akvo/lumen/endpoint/raster.clj
  backend/src/akvo/lumen/endpoint/resource.clj
  backend/src/akvo/lumen/endpoint/root.clj
  backend/src/akvo/lumen/endpoint/share.clj
  backend/src/akvo/lumen/endpoint/split_column.clj
  backend/src/akvo/lumen/endpoint/tier.clj
  backend/src/akvo/lumen/endpoint/transformation.clj
  backend/src/akvo/lumen/endpoint/user.clj
  backend/src/akvo/lumen/endpoint/visualisation.clj
  backend/src/akvo/lumen/lib/user.clj
  backend/src/akvo/lumen/main.clj
  backend/src/akvo/lumen/monitoring.clj
  backend/test/akvo/lumen/auth_test.clj
  backend/test/akvo/lumen/endpoint/files_test.clj
  backend/test/akvo/lumen/endpoint/job_execution_test.clj
  backend/test/akvo/lumen/endpoint/library_test.clj
  backend/test/akvo/lumen/endpoint/root_test.clj
  backend/test/akvo/lumen/endpoint/transformation_test.clj
  backend/test/akvo/lumen/endpoint/visualisation_test.clj
  backend/test/akvo/lumen/endpoints_test.clj
  backend/test/akvo/lumen/endpoints_test/commons.clj
  backend/test/akvo/lumen/fixtures.clj
  backend/test/akvo/lumen/test_utils.clj
  backend/test/akvo/lumen/utils/local_server.clj
  backend/test/resources/endpoints-test.edn
  backend/test/resources/sample-data-1.csv
  backend/test/resources/test.edn
Labels: in progress

#2029 #1973 Colour picker showing in shared dashboards/visuals
  client/src/components/charts/ScatterChart.jsx
Labels: ready for testing

#2027 #2008 Stacked/Split bar's legend position does not change
  client/src/components/charts/StackedBarChart.jsx
  client/src/components/charts/StackedBarChartHorizontal.jsx
Labels: ready for testing

#2026 #1997 Horizontal percentage stacked bars
  client/src/components/charts/StackedBarChartHorizontal.jsx
Labels: ready for testing

#2033 Ensure edn files are reloaded with dev/go (connect #2032)
  backend/dev/src/dev.clj
Labels: in progress

#2010 Use integrant component data spec validation approach (Connect #2009)
  backend/specs/akvo/lumen/specs.clj
  backend/specs/akvo/lumen/specs/components.clj
  backend/src/akvo/lumen/auth.clj
  backend/src/akvo/lumen/component/caddisfly.clj
  backend/src/akvo/lumen/component/emailer.clj
  backend/src/akvo/lumen/component/error_tracker.clj
  backend/src/akvo/lumen/component/handler.clj
  backend/src/akvo/lumen/component/hikaricp.clj
  backend/src/akvo/lumen/component/http.clj
  backend/src/akvo/lumen/component/keycloak.clj
  backend/src/akvo/lumen/component/tenant_manager.clj
  backend/src/akvo/lumen/endpoint/aggregation.clj
  backend/src/akvo/lumen/endpoint/collection.clj
  backend/src/akvo/lumen/endpoint/dashboard.clj
  backend/src/akvo/lumen/endpoint/data_source.clj
  backend/src/akvo/lumen/endpoint/dataset.clj
  backend/src/akvo/lumen/endpoint/env.clj
  backend/src/akvo/lumen/endpoint/export.clj
  backend/src/akvo/lumen/endpoint/files.clj
  backend/src/akvo/lumen/endpoint/healthz.clj
  backend/src/akvo/lumen/endpoint/invite.clj
  backend/src/akvo/lumen/endpoint/job_execution.clj
  backend/src/akvo/lumen/endpoint/library.clj
  backend/src/akvo/lumen/endpoint/multiple_column.clj
  backend/src/akvo/lumen/endpoint/public.clj
  backend/src/akvo/lumen/endpoint/raster.clj
  backend/src/akvo/lumen/endpoint/resource.clj
  backend/src/akvo/lumen/endpoint/share.clj
  backend/src/akvo/lumen/endpoint/split_column.clj
  backend/src/akvo/lumen/endpoint/tier.clj
  backend/src/akvo/lumen/endpoint/transformation.clj
  backend/src/akvo/lumen/endpoint/user.clj
  backend/src/akvo/lumen/endpoint/visualisation.clj
  backend/src/akvo/lumen/migrate.clj
  backend/src/akvo/lumen/monitoring.clj
  backend/src/akvo/lumen/upload.clj
  docker-compose.ci.yml
Labels: backend, development, in progress, specs

#2031 Add spec dev endpoints /spec/action/:spec-ns/:spec-id (Connect #1876)
  backend/dev/resources/dev.edn
  backend/dev/src/dev/commons.clj
  backend/dev/src/dev/endpoints.clj
  backend/dev/src/dev/endpoints/transit.clj
  backend/project.clj
  backend/resources/akvo/lumen/config.edn
  backend/src/akvo/lumen/component/handler.clj
  backend/test/akvo/lumen/endpoints_test.clj
  backend/test/akvo/lumen/endpoints_test/commons.clj
  backend/test/akvo/lumen/test_utils.clj
  backend/test/resources/endpoints-test.edn
  backend/test/resources/test.edn
Labels: in progress

#2035 Change transformation logic to be async (Connect #1993)
  backend/src/akvo/lumen/endpoint/job_execution.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/lib/job-execution.sql
  backend/src/akvo/lumen/lib/job_execution.clj
  backend/src/akvo/lumen/lib/transformation.clj
  backend/test/akvo/lumen/endpoint/share_test.clj
  backend/test/akvo/lumen/endpoints_test.clj
  backend/test/akvo/lumen/endpoints_test/commons.clj
  backend/test/akvo/lumen/lib/aggregation_test.clj
  backend/test/akvo/lumen/lib/import/csv_test.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
  backend/test/akvo/lumen/test_utils.clj
  client/src/actions/dataset.js
  client/src/actions/raster.js
  client/src/constants/dataset.js
  client/src/containers/Dataset.jsx
  client/src/containers/Transformation.jsx
Labels: backend, client, in progress, internal-improvement

#2034 Fix for error protecting dashboards (Connect #2024)
  client/src/components/modals/ShareEntity.scss
  client/src/containers/Dashboard.jsx
  client/src/utilities/visualisation.js
Labels: in progress

#2038 Revert "Change transformation logic to be async (Connect #1993)"
  backend/src/akvo/lumen/endpoint/job_execution.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/lib/job-execution.sql
  backend/src/akvo/lumen/lib/job_execution.clj
  backend/src/akvo/lumen/lib/transformation.clj
  backend/test/akvo/lumen/endpoint/share_test.clj
  backend/test/akvo/lumen/endpoints_test.clj
  backend/test/akvo/lumen/endpoints_test/commons.clj
  backend/test/akvo/lumen/lib/aggregation_test.clj
  backend/test/akvo/lumen/lib/import/csv_test.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
  backend/test/akvo/lumen/test_utils.clj
  client/src/actions/dataset.js
  client/src/actions/raster.js
  client/src/constants/dataset.js
  client/src/containers/Dataset.jsx
  client/src/containers/Transformation.jsx
Labels: in progress

#2039 Change transformation logic to be async. Second attempt (Connect #1993)
  backend/src/akvo/lumen/endpoint/job_execution.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/lib/job-execution.sql
  backend/src/akvo/lumen/lib/job_execution.clj
  backend/src/akvo/lumen/lib/transformation.clj
  backend/src/akvo/lumen/lib/transformation.sql
  backend/src/akvo/lumen/lib/update.clj
  backend/test/akvo/lumen/endpoint/share_test.clj
  backend/test/akvo/lumen/endpoints_test.clj
  backend/test/akvo/lumen/endpoints_test/commons.clj
  backend/test/akvo/lumen/lib/aggregation_test.clj
  backend/test/akvo/lumen/lib/import/csv_test.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
  backend/test/akvo/lumen/test_utils.clj
  client/src/actions/dataset.js
  client/src/actions/raster.js
  client/src/components/common/ContextMenu.scss
  client/src/components/common/ContextMenuItem.jsx
  client/src/components/dataset/ColumnHeader.jsx
  client/src/components/dataset/ColumnHeader.scss
  client/src/components/dataset/DatasetControls.jsx
  client/src/components/dataset/DatasetControls.scss
  client/src/components/dataset/DatasetTable.jsx
  client/src/components/dataset/context-menus/ColumnContextMenu.jsx
  client/src/components/dataset/sidebars/TransformationLog.jsx
  client/src/constants/dataset.js
  client/src/containers/Dataset.jsx
  client/src/containers/Notification.jsx
  client/src/containers/Notification.scss
  client/src/containers/Transformation.jsx
  client/src/domain/dataset.js
  client/src/reducers/datasets.js
Labels: in progress

#2042 Horizontal percentage stacked bars #1997
  client/src/components/charts/StackedBarChartHorizontal.jsx
Labels: in progress

#2053 Fix vector type in reitit data middleware
  backend/src/akvo/lumen/component/handler.clj
Labels: backend, bug
