Repository akvo/akvo-lumen, pull requests merged in 2019-01, with the labels that each got.

#1878 Add more work on #1858 and #1450
  backend/specs/akvo/lumen/specs/import.clj
  backend/specs/akvo/lumen/specs/import/column.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/test/akvo/lumen/lib/import/clj_data_importer.clj
  backend/test/akvo/lumen/lib/import/clj_data_importer_test.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
  backend/test/akvo/lumen/lib/transformation_test.sql
Labels: in progress

#1881 Add transformation specs (Connect #1441)
  backend/specs/akvo/lumen/specs.clj
  backend/specs/akvo/lumen/specs/import.clj
  backend/specs/akvo/lumen/specs/import/column.clj
  backend/specs/akvo/lumen/specs/import/values.clj
  backend/specs/akvo/lumen/specs/transformation.clj
  backend/src/akvo/lumen/util.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
  backend/test/akvo/lumen/test_utils.clj
  backend/test/resources/ops.json
Labels: in progress

#1891 [#1890] Add ex-info message if original `cause` ex-data is nil
  backend/src/akvo/lumen/lib/import/flow.clj
Labels: in progress

#1892 Fix a.l.l.transformation.merge-datasets/distinct-columns
  backend/src/akvo/lumen/lib/transformation/merge_datasets.clj
  backend/test/akvo/lumen/lib/transformation/merge_datasets_test.clj
Labels: in progress

#1894 Change transformation.op to string type
  backend/specs/akvo/lumen/specs/transformation.clj
  backend/src/akvo/lumen/lib/transformation/change_datatype.clj
  backend/src/akvo/lumen/lib/transformation/combine.clj
  backend/src/akvo/lumen/lib/transformation/delete_column.clj
  backend/src/akvo/lumen/lib/transformation/derive.clj
  backend/src/akvo/lumen/lib/transformation/engine.clj
  backend/src/akvo/lumen/lib/transformation/filter_column.clj
  backend/src/akvo/lumen/lib/transformation/geo.clj
  backend/src/akvo/lumen/lib/transformation/merge_datasets.clj
  backend/src/akvo/lumen/lib/transformation/multiple_column.clj
  backend/src/akvo/lumen/lib/transformation/rename_column.clj
  backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj
  backend/src/akvo/lumen/lib/transformation/sort_column.clj
  backend/src/akvo/lumen/lib/transformation/split_column.clj
  backend/src/akvo/lumen/lib/transformation/text.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
  backend/test/akvo/lumen/test_utils.clj
Labels: in progress

#1897 Fixed type wich -> which in error message (Connect #1896)
  backend/src/akvo/lumen/lib/transformation/merge_datasets.clj
Labels: in progress

#1893 Update InputFormat.md [doc] (Connect #886)
  doc/integration/InputFormat.md
Labels: in progress

#1895 Use strings instead of keywords in data values stored in postgres (Connect #1894 #1441)
  backend/specs/akvo/lumen/specs/import.clj
  backend/specs/akvo/lumen/specs/import/column.clj
  backend/specs/akvo/lumen/specs/import/values.clj
  backend/src/akvo/lumen/lib/import.clj
  backend/src/akvo/lumen/lib/import/common.clj
  backend/src/akvo/lumen/lib/import/csv.clj
  backend/src/akvo/lumen/lib/import/flow_common.clj
  backend/src/akvo/lumen/lib/import/flow_v2.clj
  backend/src/akvo/lumen/lib/import/flow_v3.clj
  backend/src/akvo/lumen/lib/multiple_column.clj
  backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj
  backend/src/akvo/lumen/lib/transformation/split_column.clj
  backend/src/akvo/lumen/lib/update.clj
  backend/src/akvo/lumen/postgres.clj
  backend/src/akvo/lumen/protocols.clj
  backend/test/akvo/lumen/lib/multiple_column_test.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
  backend/test/akvo/lumen/lib/update_test.clj
  backend/test/akvo/lumen/test_utils.clj
Labels: in progress

#1899 Cypress tests for changing visualisation types #1866
  client/e2e-test/cypress/integration/index.spec.js
  client/e2e-test/sample-data-1.csv
  client/src/components/visualisation/configMenu/BarConfigMenu.jsx
  client/src/components/visualisation/configMenu/LineConfigMenu.jsx
  client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx
  client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
Labels: in progress

#1904 #1866 updated cypress test data url
  client/e2e-test/cypress/integration/index.spec.js
Labels: in progress

#1903 Fix transformation.change-datatype/parseFormat spec
  backend/test/akvo/lumen/lib/transformation_test.clj
Labels: in progress

#1906 #1866 Scrollbar componnet clean up recalc hanlder on unmount
  client/e2e-test/cypress/integration/index.spec.js
  client/src/components/common/ScrollBar.jsx
Labels: in progress

#1907 Bar visualisation client UI doesn't call aggregation backend API #1900
  client/src/utilities/aggregation.js
Labels: in progress

#1909 Lumen blank in Internet Explorer WIP #1902
  client/.babelrc
Labels: in progress

#1916 Comment cypress problem [client] [tests]
  client/e2e-test/cypress/integration/index.spec.js
Labels: bug, client, in progress, tests

#1918 #1902 ie11 blank
  client/.babelrc
  client/e2e-test/cypress/integration/index.spec.js
  client/package-lock.json
  client/package.json
  client/src/app.jsx
  client/src/auth.js
  client/src/components/dashboard/DashboardHeader.jsx
  client/src/components/visualisation/VisualisationHeader.jsx
  client/webpack.config.dev.js
  client/webpack.config.prod.js
Labels: in progress

#1919 uncomment changing vis type cypress tests #1902
  client/e2e-test/cypress/integration/index.spec.js
Labels: in progress

#1912 Change to optional: transformation.change-datatyoe/parseFormat spec
  backend/specs/akvo/lumen/specs/transformation.clj
  backend/test/akvo/lumen/lib/transformation_test.clj
Labels: backend, in progress, specs

#1913 Speed up aggregation dataset query
  backend/src/akvo/lumen/lib/aggregation.clj
  backend/src/akvo/lumen/lib/dataset.sql
Labels: backend, db, in progress

#1920 #1902 added string polyfills
  client/src/polyfill.js
Labels: in progress

#1910 Add import and aggregation dev utils
  backend/dev/src/dev.clj
  backend/dev/src/dev/aggregation.clj
  backend/dev/src/dev/commons.clj
  backend/dev/src/dev/import.clj
Labels: backend, in progress, utils

#1905 #1866 force click on links in cypress tests
  client/e2e-test/cypress.json
  client/e2e-test/cypress/integration/index.spec.js
  client/e2e-test/sample-data-1.csv
  client/package-lock.json
Labels: ready for testing

#1911 Refactor aggregation ns(s) and Keywordize keys
  backend/src/akvo/lumen/endpoint/aggregation.clj
  backend/src/akvo/lumen/lib/aggregation.clj
  backend/src/akvo/lumen/lib/aggregation/bar.clj
  backend/src/akvo/lumen/lib/aggregation/bubble.clj
  backend/src/akvo/lumen/lib/aggregation/commons.clj
  backend/src/akvo/lumen/lib/aggregation/line.clj
  backend/src/akvo/lumen/lib/aggregation/pie.clj
  backend/src/akvo/lumen/lib/aggregation/pivot.clj
  backend/src/akvo/lumen/lib/aggregation/scatter.clj
  backend/src/akvo/lumen/lib/dataset/utils.clj
  backend/src/akvo/lumen/lib/public.clj
  backend/src/akvo/lumen/lib/transformation/derive.clj
  backend/src/akvo/lumen/lib/transformation/merge_datasets.clj
  backend/src/akvo/lumen/lib/transformation/multiple_column.clj
  backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj
  backend/src/akvo/lumen/lib/transformation/split_column.clj
  backend/src/akvo/lumen/lib/visualisation/map_config.clj
  backend/src/akvo/lumen/lib/visualisation/maps.clj
  backend/src/akvo/lumen/postgres/filter.clj
  backend/test/akvo/lumen/lib/aggregation/scatter_test.clj
  backend/test/akvo/lumen/lib/aggregation_test.clj
  backend/test/akvo/lumen/lib/pie_test.clj
  backend/test/akvo/lumen/lib/pivot_test.clj
  backend/test/akvo/lumen/test_utils.clj
Labels: backend, in progress, specs, tests

#1898 Client request error handling #1838
  client/src/actions/collection.js
  client/src/actions/dashboard.js
  client/src/actions/dataset.js
  client/src/actions/library.js
  client/src/actions/raster.js
  client/src/actions/visualisation.js
  client/src/api.js
  client/src/app-pub.jsx
  client/src/app.jsx
  client/src/components/Resources.jsx
  client/src/components/Users.jsx
  client/src/components/dataset/sidebars/ExtractMultiple.jsx
  client/src/components/dataset/sidebars/SplitColumn.jsx
  client/src/components/modals/createDataset/AkvoFlowDataSourceSettings.jsx
  client/src/components/modals/createDataset/DataFileDataSourceSettings.jsx
  client/src/components/modals/createDataset/GeoTIFFDataSourceSettings.jsx
  client/src/components/visualisation/VisualisationEditor.jsx
  client/src/containers/Dashboard.jsx
  client/src/containers/Dataset.jsx
  client/src/containers/Raster.jsx
  client/src/containers/Transformation.jsx
  client/src/utilities/api.js
  client/src/utilities/auth.js
Labels: ready for testing

#1932 #1866 cypress test fixes
  client/e2e-test/cypress/integration/index.spec.js
  client/src/components/charts/BubbleChart.jsx
  client/src/components/charts/LineChart.jsx
  client/src/components/charts/PieChart.jsx
  client/src/components/charts/PolarAreaChart.jsx
  client/src/components/charts/ScatterChart.jsx
  client/src/components/charts/SimpleBarChart.jsx
  client/src/components/charts/SimpleBarChartHorizontal.jsx
  client/src/components/charts/StackedBarChart.jsx
  client/src/components/charts/StackedBarChartHorizontal.jsx
Labels: in progress

#1933 #1779 Show Keep/Remove with filter in visualisation editor
  client/src/components/visualisation/configMenu/FilterMenu.jsx
Labels: ready for testing

#1934 #1738 remove help button from exports
  client/src/components/charts/SimpleBarChart.jsx
  client/src/components/charts/SimpleBarChartHorizontal.jsx
  client/src/containers/Dashboard.jsx
  client/src/containers/Notification.scss
Labels: ready for testing

#1935 #1739 Remove zoom buttons when exporting maps
  client/src/components/charts/MapVisualisation.jsx
  client/src/components/dashboard/DashboardCanvasItem.jsx
  client/src/components/dashboard/DashboardEditor.jsx
  client/src/components/visualisation/VisualisationEditor.jsx
  client/src/components/visualisation/VisualisationPreview.jsx
Labels: in progress
